services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  utbots:
    build:
      context: .
    command: bundle exec rails server -b '0.0.0.0'
    tty: true
    stdin_open: true
    environment:
      RAILS_LOG_TO_STDOUT: 1
      RAILS_MAX_THREADS: 5
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    healthcheck:
      disable: true
    volumes:
      - .:/app
      - bundle_cache:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  bundle_cache:
  postgres_data:
