name: Test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_call:

env:
  # DATABASE_URL: "postgres://test_username:test_password@localhost:5432/test_database"
  RUBY_VERSION: 3.4.7
  RAILS_ENV: test
  TZ: Europe/Amsterdam
  BUNDLE_WITHOUT: production
  BUNDLE_DEPLOYMENT: false

jobs:
  # bundle-audit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ env.RUBY_VERSION }}
  #         bundler-cache: true

  #     - name: Run bundle audit
  #       # uri gem cannot be updated in current production OS
  #       run: |
  #         bundle exec bundle audit check --update --ignore CVE-2023-26141 CVE-2023-28755 CVE-2023-36617 CVE-2025-27111

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{env.RUBY_VERSION}}
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop

  # brakeman:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ${{env.RUBY_VERSION}}
  #         bundler-cache: true

  #     - name: Run brakeman
  #       run: bundle exec brakeman

  # minitest:
  #   runs-on: ubuntu-latest

  #   services:
  #     postgres:
  #       image: postgres:14-alpine
  #       env:
  #         POSTGRES_DB: test_database
  #         POSTGRES_PASSWORD: test_password
  #         POSTGRES_USER: test_username
  #       ports:
  #         - 5432:5432
  #       options:
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ env.RUBY_VERSION }}
  #         bundler-cache: true

  #     - name: Set up Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'yarn'
  #         cache-dependency-path: yarn.lock

  #     - name: Yarn install
  #       run: |
  #         yarn install

  #     - name: Precompile assets
  #       run: |
  #         bundle exec rails assets:precompile

  #     - name: Set config files
  #       run: |
  #         cp config/database.yml.example config/database.yml

  #     - name: Create DB
  #       run: |
  #         bundle exec rails db:create
  #         bundle exec rails db:schema:load

  #     - name: Run Minitest
  #       run: |
  #         bundle exec rails test
